#!/bin/bash

# Read the input from stdin
while read local_ref local_sha remote_ref remote_sha; do
    # Get the list of files that are being pushed
    files=$(git diff --name-only $local_sha $remote_sha)

    # Define the directories to check
    restricted_dirs=("src/app" "include/app" "android" "src/platform" "include/platorm")

    # Check if any of the changed files are in the restricted directories
    for dir in "${restricted_dirs[@]}"; do
        if echo "$files" | grep -q "^$dir/"; then
            echo "Push to 'origin' is denied because changes were made in $dir."
            exit 1
        fi
    done
done

exit 0

